# Training Configuration
training:
  # Basic settings
  epochs: 60
  batch_size: 128
  num_workers: 4
  pin_memory: true
  
  # Optimizer
  optimizer:
    type: "adamw"
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  # Learning rate scheduler
  scheduler:
    type: "reduce_on_plateau"  # reduce_on_plateau, cosine, step
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: 1.0e-6
  
  # Mixed precision training
  mixed_precision: true
  
  # Curriculum learning
  curriculum:
    enabled: true
    stage1_epochs: 15  # Easy puzzles (30-40 clues)
    stage2_epochs: 20  # Medium puzzles (22-35 clues)
    stage3_epochs: 25  # Hard puzzles (17-25 clues)
    
    difficulty_ranges:
      easy: [30, 40]    # Number of given clues
      medium: [22, 35]
      hard: [17, 25]
  
  # Data augmentation
  augmentation:
    digit_permutation: 0.2     # Randomly swap digit labels
    rotation: 0.25             # Random 90°/180°/270° rotation
    transpose: 0.15            # Transpose rows/columns
    row_col_permutation: 0.20  # Swap rows/cols within bands
  
  # Regularization
  dropout: 0.3
  label_smoothing: 0.0
  gradient_clip: 1.0
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  
  # Checkpointing
  checkpoint:
    save_every: 5        # Save every N epochs
    save_best: true
    save_last: true
    monitor: "val_accuracy"
    mode: "max"
  
  # Validation
  val_split: 0.2
  val_every: 1  # Validate every N epochs
  
  # Loss function
  loss:
    type: "cross_entropy"
    constraint_penalty: 0.1  # Weight for constraint violation penalty
    
# Logging
logging:
  use_wandb: false
  project: "sudoku-ai"
  log_every: 100  # Log every N batches
  
  metrics:
    - cell_accuracy
    - grid_accuracy
    - constraint_violations
    - solve_rate

# Hardware
device: "cuda"  # cuda, cpu, mps
deterministic: false
seed: 42
